[[keybind]]
command = "Execute"
value = "ghostty"
modifier = "Mod4"
key = "Return"

[[keybind]]
command = "Execute"
value = "rofi -show drun"
modifier = "Mod4"
key = "d"

[[keybind]]
command = "CloseWindow"
modifier = "Mod4|Shift"
key = "q"

[[keybind]]
command = "SwapTags"
modifier = "Mod4|Shift"
key = "Up"

[[keybind]]
command = "SwapTags"
modifier = "Mod4|Shift"
key = "Down"

[[keybind]]
command = "MoveWindowUp"
modifier = "Mod4|Shift"
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = "Mod4|Shift"
key = "j"

[[keybind]]
command = "FocusNextTag"
modifier = "Mod4"
key = "l"

[[keybind]]
command = "FocusPreviousTag"
modifier = "Mod4"
key = "h"

[[keybind]]
command = "FocusWindowUp"
modifier = "Mod4"
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = "Mod4"
key = "j"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = "Mod4"
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = "Mod4"
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = "Mod4"
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = "Mod4"
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = "Mod4"
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = "Mod4"
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = "Mod4"
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = "Mod4"
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = "Mod4"
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = "Mod4|Shift"
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = "Mod4|Shift"
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = "Mod4|Shift"
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = "Mod4|Shift"
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = "Mod4|Shift"
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = "Mod4|Shift"
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = "Mod4|Shift"
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = "Mod4|Shift"
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = "Mod4|Shift"
key = "9"
